name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # better relevancy for analysis

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"   # match sonar.python.version (use "3.12" if 3.13 isn't available)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if exist requirements.txt (pip install -r requirements.txt)
          pip install pytest coverage

      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage xml -o coverage.xml
        # If your tests need env vars, add them here via 'env:'

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
